#pragma once

#include "optick.h"

#ifdef DAR_PROFILE
#define DAR_OPTICK_START    OPTICK_START_CAPTURE
#define DAR_OPTICK_STOP     OPTICK_STOP_CAPTURE
#define DAR_OPTICK_SAVE     OPTICK_SAVE_CAPTURE

#define DAR_OPTICK_APP      OPTICK_APP
#define DAR_OPTICK_FRAME    OPTICK_FRAME
#define DAR_OPTICK_EVENT    OPTICK_EVENT
#define DAR_OPTICK_THREAD   OPTICK_THREAD
#define DAR_OPTICK_TAG      OPTICK_TAG
#define DAR_OPTICK_SHUTDOWN OPTICK_SHUTDOWN
#else
#define DAR_OPTICK_APP
#define DAR_OPTICK_FRAME
#define DAR_OPTICK_EVENT
#define DAR_OPTICK_THREAD
#define DAR_OPTICK_TAG
#define DAR_OPTICK_SHUTDOWN
#endif // DAR_PROFILE